### ISSUE TITLE
High level python api

### ISSUE THREAD

**Issue by soerendip** [Arseha/peakonly#12]
Hi, 

I put your code into an installable python module with a user-friendly, high-level API. 
Have a look at the example Jupyter notebook too.

https://github.com/soerendip/ms-peakonly

I found it difficult to use the code interactively, therefore I created this. After `pip install ... ` the module can be imported as any other python library. 

I also added a little comparison with another metabolomics program and compared the extracted values. I think both programs use a different strategy for mz-width. Which creates a little discrepancy between the outputs. 

Cheers, and good work!

**Comment by Arseha** [comment]
Hi, 

It's cool, thanks! I've added a link to your project in README.md. 

We are now working on a major restructuring of a project (it would be a really brand new `peakonly` with much better code quality and stability). If you have the opportunity or desire to work with us, write an email (melnikov.arsenty@gmail.com). Any help or advice would be appreciated.
