### ISSUE TITLE
Json file creation from a custom dataset and Json interpretation. 

### ISSUE THREAD

**Issue by ankitshah009** [Arseha/peakonly#2]
Looking for scripts that are able to create the json file for a custom dataset or json from a single mzML file and how the json files can be interpreted. 

For example, some json files post downloading are labeled with only numerics like 991.json and there are files consisting e962.json. Is there any specific reason for this labeling of the json files in the training, validation and testing?

**Comment by Arseha** [comment]
We are definitely planning for the creation of such a script, hope even with a GUI. For now, I only have *.ipynb file that was used for dataset creation. Ready to send it to anyone with a need via email (just let me know). 

> For example, some json files post downloading are labeled with only numerics like 991.json and there are files consisting e962.json. Is there any specific reason for this labeling of the json files in the training, validation and testing?

There are no specific reasons for it. In fact, the annotation of files with beginning with 'e' (stands for 'extra') was performed in a semi-automatic manner. We used predictions of previously trained CNNs (on a smaller dataset), but nevertheless we looked through all of these files and manually corrected in cases when it was needed. For your own dataset, you can freely name the files in any convenient way. Just place them inside 'train', 'test', 'val' folders.
