### ISSUE TITLE
Export feature traces as csv

### ISSUE THREAD

**Issue by quarksome** [Arseha/peakonly#6]
Hi,

I was wondering how would I go about if I want to export the traces of each detected feature as csv. Basically, I want to extract the data from the EIC plots of each feature. I tried looking at the codes but my little knowledge of Python could not comprehend where I can make some edits. I was thinking it will be doable since the trace data are already being used to generate the plots. I just need to know how to (1) extract the trace for each feature (does the feature has this method?), and (2) where to insert a snippet of code to export it as .csv (I was thinking maybe exporting it as another csv file during "Save a .csv file with detected features".

I appreciate any feedback about this. Thank you!

**Comment by Arseha** [comment]
Hi, 

Possibly I didn't quite get in which format you want to save the data from the EIC plots of each feature, but I've added a possibility to save detected features as a separate *.csv files (with information about intensities and peak's boundaries). It is available [here: branch ISSUE-6](https://github.com/Arseha/peakonly/tree/ISSUE-6). (File -> Save -> Save features traces as *.csv files). At least, I hope a [comparison](https://github.com/Arseha/peakonly/compare/ISSUE-6) with `master` may be helpful to get insight on the code and how it can be changed to meet your requirements. Feel free to ask any questions and contribute to the project.

**Comment by quarksome** [comment]
That is exactly what I wanted! Thank you!!
